### ISSUE TITLE
conda env create -n team -f env.yml 実行時にエラーが発生する

### ISSUE THREAD

**Issue by tana-kase** [welshonion/team-project-l#1]
### condaで仮想環境を作る際のエラー
以下ログです。
```
Collecting package metadata (repodata.json): done
Solving environment: failed
ResolvePackageNotFound: 
  - python==3.8.15=h6244533_2
  - vc==14.2=h21ff451_1
  - ca-certificates==2022.10.11=haa95532_0
  - libffi==3.4.2=hd77b12b_6
  - sqlite==3.40.0=h2bbff1b_0
  - pip==22.3.1=py38haa95532_0
  - setuptools==65.5.0=py38haa95532_0
  - vs2015_runtime==14.27.29016=h5e58377_2
  - certifi==2022.12.7=py38haa95532_0
  - wincertstore==0.2=py38haa95532_2
  - openssl==1.1.1s=h2bbff1b_0
```
いくつかosのライブラリのバージョンに食い違いがあるようです。
ビルド環境のないバージョンのymlファイルをもらっても良いですか？(それかpipの内容をrequirements.txtに取り出してもいいのかな?)
以下のコマンドできるようです。
```
$ conda env export --no-builds > env.yml
$ conda env create --file env.yaml
```
[anacondaでyamlファイルから仮想環境が作れない場合の対処法](https://qiita.com/hayato1130/items/676894f7e7dd0e9fe527)

**Comment by welshonion** [comment]
基本的な処理しかしていないので、任意のpython3.8環境にFlaskとrequestsあたりをインストールすればひとまず動作はすると思います。
このへんの実行環境については(Anacondaが適切かも含めて)次回話したほうが良いかと思っています。

**Comment by tana-kase** [comment]
了解です.
yamlファイル自体はdockerの環境構築にも使えるので、使い道ありますね
ちなみに私もAnaconda使っています
